/**
 * Split Merger
 * The Split and Merge API allows you to split and merge files. For now you always have to define the filetype for the split or merge result. Supported types are Tiff, PDF or MS word files. In the future new types as well as type inferring will be implemented. Please note that this API will change in the way the merge or split is initiated from v0.1 to v0.2 which is scheduled later in 2017.
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['SphereonSDKSplitMerge/ApiClient', 'SphereonSDKSplitMerge/model/BackendSettings'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./BackendSettings'));
  } else {
    // Browser globals (root is window)
    if (!root.SplitMerger) {
      root.SplitMerger = {};
    }
    root.SplitMerger.JobSettings = factory(root.SplitMerger.ApiClient, root.SplitMerger.BackendSettings);
  }
}(this, function(ApiClient, BackendSettings) {
  'use strict';




  /**
   * The JobSettings model module.
   * @module SphereonSDKSplitMerge/model/JobSettings
   * @version 0.1
   */

  /**
   * Constructs a new <code>JobSettings</code>.
   * Job settings
   * @alias module:SphereonSDKSplitMerge/model/JobSettings
   * @class
   * @param storageProvider {module:SphereonSDKSplitMerge/model/JobSettings.StorageProviderEnum} The provider of the storage backend
   * @param engine {module:SphereonSDKSplitMerge/model/JobSettings.EngineEnum} The quality of the action engine that will be used to process the job
   */
  var exports = function(storageProvider, engine) {
    var _this = this;


    _this['storageProvider'] = storageProvider;
    _this['engine'] = engine;
  };

  /**
   * Constructs a <code>JobSettings</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:SphereonSDKSplitMerge/model/JobSettings} obj Optional instance to populate.
   * @return {module:SphereonSDKSplitMerge/model/JobSettings} The populated <code>JobSettings</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('backendSettings')) {
        obj['backendSettings'] = BackendSettings.constructFromObject(data['backendSettings']);
      }
      if (data.hasOwnProperty('storageProvider')) {
        obj['storageProvider'] = ApiClient.convertToType(data['storageProvider'], 'String');
      }
      if (data.hasOwnProperty('engine')) {
        obj['engine'] = ApiClient.convertToType(data['engine'], 'String');
      }
    }
    return obj;
  }

  /**
   * Settings of the storage backend
   * @member {module:SphereonSDKSplitMerge/model/BackendSettings} backendSettings
   */
  exports.prototype['backendSettings'] = undefined;
  /**
   * The provider of the storage backend
   * @member {module:SphereonSDKSplitMerge/model/JobSettings.StorageProviderEnum} storageProvider
   */
  exports.prototype['storageProvider'] = undefined;
  /**
   * The quality of the action engine that will be used to process the job
   * @member {module:SphereonSDKSplitMerge/model/JobSettings.EngineEnum} engine
   */
  exports.prototype['engine'] = undefined;


  /**
   * Allowed values for the <code>storageProvider</code> property.
   * @enum {String}
   * @readonly
   */
  exports.StorageProviderEnum = {
    /**
     * value: "API_SUPPLIER"
     * @const
     */
    "SUPPLIER": "API_SUPPLIER"  };

  /**
   * Allowed values for the <code>engine</code> property.
   * @enum {String}
   * @readonly
   */
  exports.EngineEnum = {
    /**
     * value: "BASIC"
     * @const
     */
    "BASIC": "BASIC",
    /**
     * value: "ADVANCED"
     * @const
     */
    "ADVANCED": "ADVANCED",
    /**
     * value: "PREMIUM"
     * @const
     */
    "PREMIUM": "PREMIUM"  };


  return exports;
}));


