/* 
 * Split Merger
 *
 * The Split and Merge API allows you to split and merge files. For now you always have to define the filetype for the split or merge result. Supported types are Tiff, PDF or MS word files. In the future new types as well as type inferring will be implemented. Please note that this API will change in the way the merge or split is initiated from v0.1 to v0.2 which is scheduled later in 2017.
 *
 * OpenAPI spec version: 0.1
 * Contact: dev@sphereon.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Sphereon.SDK.SplitMerge.Model
{
    /// <summary>
    /// BackendSettings
    /// </summary>
    [DataContract]
    public partial class BackendSettings :  IEquatable<BackendSettings>
    {
        /// <summary>
        /// type of the backend where files will be stored
        /// </summary>
        /// <value>type of the backend where files will be stored</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum BackendTypeEnum
        {
            
            /// <summary>
            /// Enum FILESYSTEM for "FILESYSTEM"
            /// </summary>
            [EnumMember(Value = "FILESYSTEM")]
            FILESYSTEM,
            
            /// <summary>
            /// Enum AMAZONS3 for "AMAZON_S3"
            /// </summary>
            [EnumMember(Value = "AMAZON_S3")]
            AMAZONS3,
            
            /// <summary>
            /// Enum MSAZUREBLOBSTORAGE for "MS_AZURE_BLOB_STORAGE"
            /// </summary>
            [EnumMember(Value = "MS_AZURE_BLOB_STORAGE")]
            MSAZUREBLOBSTORAGE,
            
            /// <summary>
            /// Enum GOOGLECLOUDSTORAGE for "GOOGLE_CLOUD_STORAGE"
            /// </summary>
            [EnumMember(Value = "GOOGLE_CLOUD_STORAGE")]
            GOOGLECLOUDSTORAGE
        }

        /// <summary>
        /// type of the backend where files will be stored
        /// </summary>
        /// <value>type of the backend where files will be stored</value>
        [DataMember(Name="backendType", EmitDefaultValue=false)]
        public BackendTypeEnum? BackendType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BackendSettings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BackendSettings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BackendSettings" /> class.
        /// </summary>
        /// <param name="Container">name of the container where files will be stored (required).</param>
        /// <param name="BackendType">type of the backend where files will be stored (required).</param>
        /// <param name="Backend">name of the backend where files will be stored (required).</param>
        public BackendSettings(string Container = null, BackendTypeEnum? BackendType = null, string Backend = null)
        {
            // to ensure "Container" is required (not null)
            if (Container == null)
            {
                throw new InvalidDataException("Container is a required property for BackendSettings and cannot be null");
            }
            else
            {
                this.Container = Container;
            }
            // to ensure "BackendType" is required (not null)
            if (BackendType == null)
            {
                throw new InvalidDataException("BackendType is a required property for BackendSettings and cannot be null");
            }
            else
            {
                this.BackendType = BackendType;
            }
            // to ensure "Backend" is required (not null)
            if (Backend == null)
            {
                throw new InvalidDataException("Backend is a required property for BackendSettings and cannot be null");
            }
            else
            {
                this.Backend = Backend;
            }
        }
        
        /// <summary>
        /// name of the container where files will be stored
        /// </summary>
        /// <value>name of the container where files will be stored</value>
        [DataMember(Name="container", EmitDefaultValue=false)]
        public string Container { get; set; }
        /// <summary>
        /// name of the backend where files will be stored
        /// </summary>
        /// <value>name of the backend where files will be stored</value>
        [DataMember(Name="backend", EmitDefaultValue=false)]
        public string Backend { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BackendSettings {\n");
            sb.Append("  Container: ").Append(Container).Append("\n");
            sb.Append("  BackendType: ").Append(BackendType).Append("\n");
            sb.Append("  Backend: ").Append(Backend).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as BackendSettings);
        }

        /// <summary>
        /// Returns true if BackendSettings instances are equal
        /// </summary>
        /// <param name="other">Instance of BackendSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BackendSettings other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Container == other.Container ||
                    this.Container != null &&
                    this.Container.Equals(other.Container)
                ) && 
                (
                    this.BackendType == other.BackendType ||
                    this.BackendType != null &&
                    this.BackendType.Equals(other.BackendType)
                ) && 
                (
                    this.Backend == other.Backend ||
                    this.Backend != null &&
                    this.Backend.Equals(other.Backend)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Container != null)
                    hash = hash * 59 + this.Container.GetHashCode();
                if (this.BackendType != null)
                    hash = hash * 59 + this.BackendType.GetHashCode();
                if (this.Backend != null)
                    hash = hash * 59 + this.Backend.GetHashCode();
                return hash;
            }
        }
    }

}
